examples/patsyCategoricalDemo.py
This is a trivial fix, adding the required imports so that the patsyDemo does not throw an error.
I'm a bit confused about the value of this particular demo file, seems like it's just what the link from the user guide provides.
=> Small fix to make patsyCategoricalDemo work.

examples/bfgs_autograd.py
=> Small fix to ensure bfgs_autograd works with current scipy and numpy.

book/bernoulli_entropy_fig.py
save figure into relative ../figures/ path as .pdf file. No plot title, mirroring the matlab version.
This pull request is also a test of the process.
=> add bernoulli entropy figure plotting from the introduction

book/bayes_change_of_var.py
* Better histogram bar alignment
* Random seeding for reproducibility
* A fix to a plotting typo that prevented the script from running
* Addition of summary comments
=> Some fixes to the bayes_change_of_var script:

book/newtons_method_min_1d.py
I didn't plot labels for data 1 - 4 because I think it is much more clean this way
=> plot newtons method min 1d figure

book/shrinkcov.py, book/shrinkcov_plots.py
Please extract the covcond function to a library script if required for other book scripts.
=> Converted shrinkcovdemo.m to Python.

README.md
Cf. 4ede64b 2019-06-27 N rename book to scripts
=> Fix scripts location in README after renaming

scripts/pcaDemo2d.py
Hey, this is a PR for figure 2.70. My approach is to just recreate the image as I see it in the book, rather than tracing through the matlab code and recreate that directly. Happy to hear any feedback.
=> add pcaDemo2d for fig 2.70

scripts/spectral_clustering_demo.py
Replaces spectralClusteringDemo.m
=> Add spectral_clustering_demo.py for Figure 22.22.

scripts/bayes_opt_demo.py, scripts/bayes_opt_demo_orig.py, scripts/gpr_demo.py
First of all, thanks for mentioning example code from [my repo](https://github.com/krasserm/bayesian-machine-learning) and including it into pyprobml. The location and default branch of the linked notebooks changed meanwhile. This pull request points to the new locations.
=> Update location of original gpr and bayes_opt code

scripts/geom_ridge.py
Replicate `geomRidge.m`digram of section 11.8.
The script produces the following figure:
=> add geom_ridge diagram

scripts/vqDemo.py
Added `vqDemo.py` script for vector quantization figures.
Solves issue #236
=> Added script for vector quantization figures

scripts/hingeLossPlot.py
Replicate hingeLossPlot.m plot of section 18.7.
The script produces the following figure:
=> python hingeLossPlot implementation 18.7

scripts/pcaImageDemo.py
Added all the 5 figures for PCA demo
closes #227
=> Added pcaImageDemo

scripts/agglomDemo.py
Added python implementation of agglomDemo.
Solves #233
=> Added implementation of agglomDemo

scripts/smoothingKernelPlot.py
Converted the smoothingKernalPlot to python as mentioned in issue #214
=> Converted smoothingKernelPlot to python Fixes #214

scripts/huberLossPlot.py
Figure 17.20 a) 
Replicate huberLossPlot.m plot of Figure 17.20. 
The script produces the following figure:
=> huberLossPlot issue #183 Figure 17.20

scripts/kmeansYeastDemo.py
These are the pictures of the plots form the script.
=> add  kmeansYeastdemo_figures

scripts/gaussInferParamsMean2d.py
@mjsML  Added gaussInferParamsMean2d
closes #172
figure :
=> gaussInferParamsMean2d

scripts/emLogLikelihoodMax.py
=> Convert emLogLikelihoodMax to python

scripts/regtreeSurfaceDemo.py
Implementing regtreeSurfaceDemo which creates Figure 18.1
=> Figure 18.1

scripts/pcaEmStepByStep.py
@mjsML 
Here are the figures
Solves #229
=> pcaEmStepByStep

scripts/mixGaussLikSurfaceDemo.py
=> Converted mixGaussLikSurfaceDemo to python 

scripts/generativeVsDiscrim.py
=> Converted generativeVsDiscrim to python

scripts/KLfwdReverseMixGauss.py
Python implementation for KLfwdReverseMixGauss
Fixes #188
=> Added python script for KLfwdReverseMixGauss

scripts/gaussInterpDemoStable.py
=> Converted gaussInterpDemoStable to python

scripts/kpcaScholkopf.py
Added python implement for kpcaScholkopf.py
Fixes #232
=> Added implementation for kpcaScholkopf

scripts/twoPowerCurves.py
=> Create twoPowerCurves.py in Python/JAX

scripts/gaussEvec.py
Python implementation of gaussEvec.m for Figure 7.6.
Figure created by python file shown below:
=> Convert gaussEvec to python (Issue-189)

scripts/bootstrapDemoBer.py
Added python implementation of bootstrapDemoBer.
Fixes #180
=> Added implementation of bootstrapDemoBer

scripts/steepestDescentDemo.py
Closes #190 
steepestDescentDemo to python
figure number 8.13
=> steepestDescentDemo to python

scripts/biasVarModelComplexity3.py
Created Bias Variance Model Complexity plot
Closes #182
=> biasVarModelComplexityV3

scripts/kernelRegressionDemo.py
Figure:
Closes #215
@murphyk, @mjsML
=> Converted kernelRegressionDemo to python

scripts/logregXorDemo.py
1) Logistic regression
2) RBF Proto
3) Poly deg 10
Closes #211
=> logregXorDemo

scripts/mlpPriorsDemo2.py
Hello, this is a Python implementation for mlpPriorsDemo2. The figures are slightly different from the book because NumPy generates different random vectors than Matlab.
=> mlpPriorsDemo2

scripts/mlpPriorsDemo2_jax.py
My implementation for mlpPriorsDemo2 using jax.
=> mlpPriorsDemo2_jax

scripts/linregOnlineDemo.py
Closes #202 
Colormap follows the follows the contribution guidelines. 
=> linregOnlineDemo

scripts/kernelBinaryClassifDemo.py
Figures:
logregL2
logregL1
(I used confidence scores to get support vectors)
RVM
SVM
(I chose the 'C' (in the range mentioned in the Matlab code) which has the max CV score)
Closes  #223
@murphyk, @mjsML
=> Converted kernelBinaryClassifDemo to python

scripts/svmCgammaDemo.py
Closes #222
@mjsML @murphyk 
(PS: 'hastieMixture.mat' seem to be unavailable in the repo, So I used it from "probml" while testing"
if it is OK I would add it in "/pyprobml/data/" and merge with this commit.)
I am not sure if CV.mean is used as the CV_estimate( I thought It would be standard error of CV.mean), But the matlab code seems to use CV.mean and I went with the same, these are the plots.
(I didn't find all the reference figures but probably mine seems to be different from them.)
Any suggestions would help me do them better :)
=> Converted svmCgammaDemo to python

scripts/logregLaplaceGirolamiDemo.py
Closes #201
This code is for figures 10.14 and 10.15 in the book
As the data is generated randomly, graphs might not look exactly similar but the same mathematics is used to create these graphs
Issue : Convert logregLaplaceGirolamiDemo to python #201
=> Converted logregLaplaceGirolamiDemo to python

scripts/gprDemoNoiseFree.py
Closes #219
Figure 1) 
Figure 2)
Figure 3)
=> gprDemoNoiseFree

scripts/linregRbfDemo.py
=> Converted linregRbfDemo to python

scripts/beta_dist_plot.py
Also: add figure title "Beta distributions" and ylabel pdf.
=> Figure 2.15: display x values in x-axis

scripts/mixBerMnistEM.py
Closes #174
The code might take some time to load and this is because it is downloading the MNIST dataset from online and the delay in execution is solely due to this and not due to the inefficiency of the code.
The values and the images will differ because the data is randomly chosen from the total set of images.
I initially added +1 to all images in the training set and changed the Bernoulli function to adapt to this, but did not see any change in the execution, It was more convenient for me to use the binary image as is and use the implementation of Bernoulli distribution which is used for this mixture model.
In this implementation, I did not find the optimal k because the optimal k=20 has already been found through trial and error in the MATLAB code and no graph implementation is …
=> Converted mixBerMnistEM to python

scripts/probitRegDemo.py
@murphyk @mjsML 
Closes #208
I tried to implement Probit Regression using EM and Minfunc(uses bfgs(or quasi-newton))  for log-likelihood estimation. I used the book and the matlab code as a guide. 
But I think LL is not converging properly😅(probably in minfunc). I request you to review this code and give suggestions
=> Converted probitRegDemo to python

scripts/betaHPD.py
Hi @murphyk and @mjsML, could you help review this code. Thanks you :)
I manage to covert betaHPD to python, here is the figures generated. 
#178
=> Converting betaHPD to python 

scripts/gpKernelPlot.py
#218 
Hello @murphyk and @mjsML please review my code and let me know what you think. I wasn't sure if the plots had to be the exact same color, I'll change them if they must match (images attached below). Thanks!
=> Converted the gpKernelPlot code

notebooks/matrix_factorization_recommender.ipynb, notebooks/matrix_factorization_recommender_surprise_lib.ipynb
@murphyk  , @mjsML  please review this.
I have refactored original notebook into two understandable notebooks.
closes #357
=> refactored matrix-factorization notebook

notebooks/skipgram_torch.ipynb
Refactored `notebooks/skipgram_torch.ipynb` by removing the use of the d2l library. I have also started attaching the Colab link in the PR for easy review.
Fixes #382 
[Colab Link](https://colab.research.google.com/drive/1uryu4yw27UhRmBSp1i5wUqo8XCJYVkiE?usp=sharing)
=> Refactored notebooks/skipgram_torch.ipynb

scripts/ugm_inf_autodiff.py
@mjsML and @murphyk please review this. Thanks :)
#384
=> Use jax.numpy consistently (ugm_inf_autodiff.py)

notebooks/multi_head_attention.ipynb
Refactored `notebooks/multi_head_attention.ipynb`
Fixes #376
=> Refactored notebooks/multi_head_attention.ipynb

notebooks/text_preproc_torch.ipynb
Refactored `notebooks/text_preproc_torch.ipynb`.
Fixes #374
=> Refactored notebooks/text_preproc_torch.ipynb

scripts/pcaoverfitdemo.py
@murphyk , @mjsML  I have made the requested changes, please review this.
closes #228 
Figures Generated:
Figure 20.6 (a)
Figure 20.6 (b)
Figure 20.7 (a)
Figure 20.7 (b)
Figure 20.8
=> Converted pcaOverfitDemo to python

notebooks/word_analogies_torch.ipynb
@murphyk I have refactored word_analogies_torch.ipynb. Could you review this PR and let me know if the changes look good to u. Then I will try to implement the same approach for other notebooks too.
Fixes #373
=> Refactored word_analogies_torch.ipynb

scripts/mixPpcaDemoNetlab.py
Closes #230,
I implemented the Probabilistic Principal Component Analysis mixture model following the research paper "Mixtures of Probabilistic Principal Component Analysers" by Michael E. Tipping and Christopher M. Bishop.
please visit pages 5-10 from http://www.miketipping.com/papers/met-mppca.pdf for the mathematics and the algorithm used in this code
I made the suggested changes:
1. Used the log sum trick everywhere
2. Changed the confidence interval to 2 standard deviations like in confidence_ellipse
=> Converted mixPpcaDemoNetlab to python

scripts/ridgePathProstate.py
@murphyk , @mjsML  please review this.
closes #204 
Generated Figure 11.12 (a):
=> Converted ridgePathProstate to Python

notebooks/logreg_jax.ipynb
closes #427 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/logreg_jax/notebooks/logreg_jax.ipynb
=> use jax.numpy consistently (logreg_jax.ipynb)

scripts/autodiff_logreg.py
@murphyk and @mjsML please review this. 
Closes #420
=> Use jax.numpy consistently (autodiff_logreg.py)

scripts/armijo_sgd.py
@murphyk and @mjsML please check this change. Thank you.
Closes #408
=> Changes in step function of armijo_sgd.py

scripts/lassoPathProstate.py
@murphyk , @mjsML  please review this.
closes #205 
Generated Figure 11.12 (b):
=> Converted lassoPathProstate to python

scripts/autodiff_demo.py
@murphyk and @mjsML please review this. Thanks :)
#396
=> Use jax.numpy consistently (autodiff_demo.py)

notebooks/lstm_torch.ipynb
@murphyk , @mjsML Please review this.
closes #394 
Colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/lstm-torch/notebooks/lstm_torch.ipynb
=> Refactored notebook/lstm_torch.ipynb

notebooks/rnn_torch.ipynb
closes #392 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/rnn-torch/notebooks/rnn_torch.ipynb
=> Refactored noteboks/rnn_torch.ipynb

notebooks/entailment_attention_mlp_torch.ipynb
@murphyk , @mjsML Please review this.
closes #388 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/entailment_attention_mlp_torch/notebooks/entailment_attention_mlp_torch.ipynb
=> Refactored notebooks/entailment_attention_mlp_torch

notebooks/multi_gpu_training_torch.ipynb
closes #387 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/multi-gpu-training-torch/notebooks/multi_gpu_training_torch.ipynb
=> Refactored multi_gpu_training_torch.ipynb

notebooks/densenet_torch.ipynb
closes #402 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/densenet-torch/notebooks/densenet_torch.ipynb
=> Refactored densenet_torch.ipynb

notebooks/resnet_torch.ipynb
closes #401 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/resnet-torch/notebooks/resnet_torch.ipynb
=> Refactored resnet-torch.ipynb

notebooks/batchnorm_torch.ipynb
closes #400 
Colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/batchnorm-torch/notebooks/batchnorm_torch.ipynb
=> Refactored batchnorm_torch.ipynb

notebooks/nmt_torch.ipynb
closes #386 
Colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/nmt-torch/notebooks/nmt_torch.ipynb
=> Refactor notebooks/nmt_torch.ipynb

notebooks/conv2d_torch.ipynb
Refactored `notebooks/conv2d_torch.ipynb`
Fixes #378
=> Refactored notebooks/conv2d_torch.ipynb

scripts/gaussimputationdemoem.py
@mjsML and @murphyk please review the code. Thanks :)
Figures generated:
a) Fig. 8.28 (a)
b) Fig. 8.28 (b)
=> Convert_gaussimputationdemoem_to_python

notebooks/bert_torch.ipynb
closes #385 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/bert-torch/notebooks/bert_torch.ipynb
=> Refactored bert_torch.ipynb

notebooks/gru_torch.ipynb
closes #395 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/gru-torch/notebooks/gru_torch.ipynb
=> Refactored gru_torch.ipynb

notebooks/cnn1d_sentiment_torch.ipynb
@murphyk , @mjsML Please review this.
closes #389 
colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/cnn1d-sentiment-torch/notebooks/cnn1d_sentiment_torch.ipynb
=> Refactored cnn1d_sentiment_torch.ipynb

notebooks/nmt_attention_torch.ipynb
closes #443 
colab: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/nmt_attention_torch/notebooks/nmt_attention_torch.ipynb
=> Refactored nmt_attention_torch.ipynb

scripts/groupLassoDemo.py
=> Converted groupLassoDemo to python

scripts/mixexp.py
@murphyk and @mjsML please review this. I have tried to write all the Matlab equations from scratch. I will try to improve this further if needed. Thanks :)
Closes #213 
Figures:
a)
b)
c)
d)
=> Convert mixexpDemoOneToMany to python

scripts/mlpPriorsDemo2.py
=> solves mlpPriorsDemo2.py display output issue

scripts/pgmpy_utils.py
@murphyk and @mjsML please have a look at this. I have added the required functions here.
=> Changes in pgmpy_utils.py file

scripts/kalman_tracking_demo.py, scripts/linear_dynamical_systems_lib.py
Adds: 
- `kalman_tracking_demo.py`
- ` linear_dynamical_systems_lib.py`
The script `kalman_tracking_demo.py` produces the following figures:
`Kalman_tracking_truth.png`
`Kalman_tracking_filtered.png`  
`Kalman_tracking_smoothed.png`
=> add kalman_tracking_demo.py

scripts/kernelBinaryClassifDemo.py, scripts/rvm_classifier.py
Refactored `kernelBinaryClassifDemo.py` and made a seperate file for RVC `rvm_classifier.py`
probml/hermes#63
=> Refactored kernelBinaryClassifDemo.py

scripts/linreg_impute_neocortex_numpyro.py, scripts/linreg_impute_numpyro.py, scripts/linreg_impute_pgm.py
Bayesian regression with imputation, also a demo on neocortex data and the pgm diagram for an example data.
probml/hermes#58, probml/hermes#85
=> missing data imputation for linear regression

scripts/mcmc_gmm_demo.py
Metropolis Hastings (MH) Sampling from a mixture of two 1d Gaussians using a 1d Gaussian proposal with different sigma and Gibbs sampling.
15.1, 15.5, 15.22.
**Gibbs sampling**
**Metropolis-Hastings**
**Autocorrelation functions**
Closes #18 
* Important to pip install `matplotlib==3.4.2` or older for correct display of 3d plots
=> Add mcmc_gmm_demo.py

scripts/kalman_tracking_demo.py, scripts/pyprobml_utils.py
* Refactors `plot_ellipse` function inside pyprobml_utils.py.
* kalman_tracking_demo.py now uses `plot_ellipse`
No changes in the output of the demo
=> refactor plot_ellipse, refactor kalman_tracking_demo.py

scripts/ars_demo.py, scripts/ars_envelope.py, scripts/rejection_sampling_demo.py
This is the code for converting adaptive rejection sampling demo and envelope into python
=> Converting ArsDemo and ArsEnvelope to python

scripts/rejection_sampling_demo.py
This is the code for coverting rejectionSamplingDemo to python
=> Convert rejectionSamplingDemo to python

scripts/Random_walk_0_to_20.py
Performed random walk on 0 to 20
=> Convert randomWalk0to20Demo to python

scripts/wishart.py
Plots of some samples from Wishart distribution, marginals, and correlation coefficient
=> Convert wiPlotDemo to python

scripts/Error_correcting_code_demo.py
Error-correcting code demo to python.
=> Convert errorCorrectingCodeDemo to python

scripts/sub_super_gaussian.py
Converting subSuperGaussPlot to python.
=> Convert subSuperGaussPlot to python

scripts/clip_dataloader.py
Modified clip_dataloader.py
Closes probml/hermes#128
=> cleaned up clip_dataloader

scripts/dynamical_systems_lib.py, scripts/extended_kalman_filter_demo.py
* Creates `dynamical_systems_lib.py` where the `ExtendedKalmanFilter` class is defined
* Defines `extended_kalman_filter_demo.py` 
`extended_kalman_filte_demo.py` produces the following two figures.
=> creates Extended Kalman Filter demo

scripts/fisher_discrim_vowel.py, scripts/fisher_lda_fit.py
`fisher_discrim_vowel.py ` is created and the fisher_lda fit is implimented in a seperate file `fisher_lda_fit.py` 
fig 9.6 in vol1
=> Hermes issue62

scripts/seq_logo_demo.py
Implemented DNA sequence demo
If you have any import remarks  for the reviewers to look at closer,  you can write them in detail here.
=> Convert seqlogoDemo to python

scripts/ggm_lasso_demo.py
=> Convert ggmLassoDemo to python

scripts/hmm_self_loop_dist.py
Implemented a simple Hidden Markov model with self-loops
=> Convert hmmSelfLoopDist to python

scripts/gpc_demo_2d_pytorch.py
Implemented gaussian process classifier.
=> Convert gpcDemo2d to python

scripts/pagerank_demo.py, scripts/pagerank_power_method_sparse.py, scripts/pagerank_small_plot_graph.py
- 28.6 in the vol 2 (2021-05-23)
- 28.7 in the vol 2 (2021-05-23)
=> Implement power method and matrix inversion, plot link structure

scripts/variational_mixture_gaussians.py, scripts/variational_mixture_gaussians_demo.py
Implementation of the Variational Mixture of Gaussians. TFP with Jax ™️ included
* Check instructions in `variational_mixture_gaussians_demo.py` to run in colab
```bash
pip uninstall tensorflow -y -q
pip install -Uq tfp-nightly[jax] > /dev/null
```
Important to run uninstall tf and install tfp-jax nightly for correct use
=> Variational Mixture of Gaussians

scripts/gp_spatial_demo.py
Implemented gaussian process demo with Poisson likelihood
20.4 in vol 2 (2021-05-23)
=> Convert gpSpatialDemoLaplace to python

scripts/chow_liu_tree_demo.py
Implemented `chow-liu` algorithm using` pgmpy`. 
30.5 in vol 2 (2021-05-23)
=> Convert chowliuTreeDemo to python

scripts/dynamical_systems_lib.py, scripts/ekf_vs_ukf_demo.py
* Kalman gain matrix for UKF did not consider elements in the observation
* Add missing `plt.show()` in `ekf_vs_ukf_demo.py`
=> Fix `linear_dynamical_systems_lib.py`

scripts/quantile_plot.py
=> pml.savefig quantile_plot.py

scripts/newtons_method_1d_plot.py
=> pml.savefig newtons_method_1d_plot.py

scripts/mix_gauss_singularity.py
=> pml.savefig mix_gauss_singularity.py

scripts/logreg_multiclass_demo.py
=> pml.savefig logreg_multiclass_demo.py

scripts/linreg_residuals_plot.py
=> pml.savefig linreg_residuals_plot.py

scripts/linreg_hbayes_1d_pymc3.py
@mjsML and @murphyk please review this.
=> pml.savefig linreg_hbayes_1d_pymc3.py

scripts/kmeans_voronoi_old.py
=> pml.savefig kmeans_voronoi_old.py

scripts/iris_plot.py
=> pml.savefig iris_plot.py

scripts/beta_plot_demo.py
=> pml.savefig beta_plot_demo.py

scripts/relevance_network_newsgroup_demo.py
=> Convert relevanceNetworkNewsgroupDemo to python

scripts/gmm_chooseK_pymc3.py, scripts/gmm_identifiability_pymc3.py.py
@murphyk and @mjsML, these are the files using the chemical data from probml-data repo.
=> chemical-data scripts

scripts/ekf_vs_ukf_mlp_demo.py, scripts/nlds_lib.py
-  (demo) Use `jax.random.permutation` instead of `np.random.shuffle` when creating the data (do not mix source randomness)
- (demo) Add plot of the results for intermediate steps of the algorithm to see how the posterior changes over time
- (lib) Add comment explaining how to use the `.from_base` method (usage unclear)
- (demo) Add comment that explains the dynamics of the model  is `fx(w=z(:,t-1), x=inputs(t)) = fwd_mlp(w,x)`
- (demo) Rewrite the number of variables as `nparams = (n_in + 1) * n_hidden + (n_hidden + 1) * n_out` 
Closes [issue 254](https://github.com/probml/hermes/issues/254) in Hermes.
=> Refactor `nlds_lib` and `ekf_vs_ukf_mlp_demo`

notebooks/clip_make_dataset_tpu_jax.ipynb
This Notebooks contains clip_extraction using clip_jax on TPU (Imagenette is used as the example dataset).
=> clip_extraction using clip_jax on TPU

scripts/generativeVsDiscrim.py
Added: Training and test error
e.g 4.18
You can put the figures you have attained.
You can link to the issue you have solved.
If the task is complicated, you can specify each step using check boxes so that everyone can understand what you have done and what you are going to complete.
If you have any import remarks  for the reviewers to look at closer,  you can write them in detail here.
=> Added: Plots

scripts/gauss2d_pymc3.py, scripts/kernelRegressionDemo.py, scripts/kmeans_voronoi.py, scripts/linregOnlineDemo.py, scripts/nat_grad_demo.py
@murphyk and @mjsML please review these files.
=> pml_savefig_batch6

scripts/gprDemoNoiseFree.py, scripts/linreg_sgd_pt.py, scripts/neymanPearson2.py, scripts/sensor_fusion_2d.py, scripts/vae_conv_load.py
@murphyk and @mjsML please review these files.
=> pml_savefig_batch4

scripts/armijo_mnist_demo.py, scripts/bayes_opt_demo_orig.py, scripts/bayes_unigauss_2d_pymc3.py, scripts/hbayes_binom_covid_uninf_pymc3.py, scripts/huberLossPlot.py, scripts/linreg_poly_vs_degree.py, scripts/mc_estimate_pi.py, scripts/poisson_dist_plot.py, scripts/posteriorGrid2d.py, scripts/svm_classifier_2d.py
@murphyk and @mjsML please review thse files.
=> pml_savefig_batch3

scripts/bayes_opt_demo_orig.py, scripts/bayes_unigauss_2d_pymc3.py, scripts/huberLossPlot.py, scripts/poisson_dist_plot.py, scripts/svm_classifier_2d.py
@murphyk and @mjsML please review these files.
=> pml_savefig_batch2

scripts/dirichlet_3d_spiky_plot.py, scripts/iris_linreg.py, scripts/learning_rate_plot.py, scripts/prior_post_pred_binom_pymc3.py
@murphyk and @mjsML please review these files.
=> pml_savefig_batch1

scripts/anscombes_quartet.py, scripts/datasaurus_dozen.py, scripts/datasaurus_dozen_together.py
Plots of Anscombe's quarte and Datasaurus Dozen datasets with their statistical properties.
=> Anscombe's plot and Datsaurus plot

scripts/emnist_data_viz_lightning.py
PL data module for EMNIST dataset.
=> PL datamodule

scripts/anscombes_quartet.py
=> anscombes quartet

scripts/datasaurus_dozen.py
Plots of datasaurus dozen dataset.
=> Plot both ways

scripts/ekf_vs_ukf_mlp_demo.py, scripts/nlds_lib.py
* UKF now takes an optional prior covariance matrix
* Fix `ekf_vs_ukf_mlp_demo.py` for UKF to work with the same priors
Closes [issue 270](https://github.com/probml/hermes/issues/270) in Hermes
=> Fix UKF prior

.gitignore, scripts/ekf_mlp_anim_demo.py, scripts/ekf_vs_ukf_mlp_demo.py
* Create UKF + MPL `.mp4` animation
https://user-images.githubusercontent.com/4108759/125843287-1ac08592-6544-4def-b86b-876a633952fc.mp4
Closes [Issue 255](https://github.com/probml/hermes/issues/255) in Hermes
=> EKF + MLP animation

scripts/bootstrap_filter_demo.py, scripts/nlds_lib.py
Implementation of the "condensation algorithm" in Jax for normal state-observed systems
Closes [issue 215](https://github.com/probml/hermes/issues/215) in Hermes
=> Create condensation algorithm / bootstrap filter demo

scripts/linreg_eb_modelsel_vs_n.py
* Fixes model selection plot
* Figure 5.6 PML Vol1
* Figure 5.7 PML Vol1
Model selection with 30 data-points
Model selection with 5 data-points
Closes [issue 251](https://github.com/probml/hermes/issues/251) in Hermes
=> refactor: `linreg_eb_modelsel_vs_n.py`

scripts/mfa_celeba_helpers.py
Helper functions for mix PPCA.
=> mix PPCA mfa helper functions

scripts/mix_bernoulli_em_mnist.py, scripts/mix_bernoulli_lib.py, scripts/mix_bernoulli_sgd_mnist.py
Implements Bernoulli mixture model.
=> Create mix_bernoulli_lib and its demos

scripts/mean_shift_segmentation.py
=> mean_shift_segmentation

scripts/mix_gauss_em_faithful.py, scripts/mix_gauss_lib.py, scripts/mix_gauss_mle_vs_map_jax.py, scripts/mix_gauss_sgd_faithful.py
Implements Gaussian Mixture Models
=> Implement mix_gauss_lib and its demos

scripts/vae/configs/vq_vae.yaml, scripts/vae/experiment.py, scripts/vae/models/pixel_cnn.py, scripts/vae/models/vq_vae.py, scripts/vae/run_pixel.py
Adds PixelCNN model, PixelCNN training and codebook sampling.
I will add the figures once the training is finished.
Closes [Issue 352](https://github.com/probml/hermes/issues/352) on Hermes
- I can finetune the hyperparameters, so they can be changed in the future.
=> PixelCNN and Codebook Sampling

scripts/hclust_yeast_demo.py
=> hclust_yeast_demo

scripts/svmCgammaDemo.py
=> svmCgammaDemo

scripts/mix_gauss_demo_faithful.py
=> mix_gauss_demo_faithful

scripts/variational_mixture_gaussians_demo.py
=> variational_mixture_gaussians_demo

scripts/fisher_discrim_vowel.py
=> fisher_discrim_vowel

scripts/dpm_sample_demo.py
Convert dpmSample.m to python.
28.4 in the vol 2 (2021-06-14)
Closes #611
=> convert dpmSample.m to python.

scripts/mix_gauss_em_faithful.py
=> mix_gauss_em_faithful

scripts/lassoPathProstate.py
=> lassoPathProstate

scripts/pca_digits.py
=> pca_digits

scripts/mix_gauss_sgd_faithful.py
=> mix_gauss_sgd_faithful

scripts/kmeans_yeast_demo.py
=> kmeans_yeast_demo

scripts/height_weight_whiten_plot.py
=> height_weight_whiten_plot

scripts/ising_image_denoise_demo.py
=> ising_image_denoise_demo

scripts/yeast_data_viz.py
=> yeast_data_viz

scripts/prostate_comparison.py
=> prostate_comparison

scripts/pagerank_demo_harvard.py
=> pagerank_demo_harvard

scripts/conditional_bernoulli_mix_lib.py, scripts/conditional_bernoulli_mix_utils.py, scripts/noisy_spelling_hmm.py
Once it is merged into pyprobml, I will add a demo, which shows how to  fit a class-conditional BMM and obtains the following figures,  into probml-noteboooks
Closes [Hermes Issue363](https://github.com/probml/hermes/issues/363)
=> Noisy spelling

scripts/thompson_sampling_bernoulli.py
Create demo of multi-armed bandit problem using Thompson sampling. Each figure is stored in an individual filename `thompson_sampling_bernoulli_w{k}_t{t}.pdf`, where `k` is the index of the arm and `t` is the iteration number. 
Putting all the figures together results in the following image
=> create: `thompson_sampling_bernoulli.py`

scripts/thompson_sampling_linear_gaussian.py
Demo of Thompson sampling for a linear Gaussian model
<p align="left">
</p>
Closes [issue 21](https://github.com/gerdm/probml-research/issues/21) in probml-research
=> feat: `thompson_sampling_linear_gaussian.py`

scripts/intrinsic_dimension_toy_demo.py
Reproduce Figure 1 from the paper "Measuring the intrinsic dimension of objective landscapes" (2018) by Chunyuan Li, et. al.
Closes [Issue#7](https://github.com/gerdm/probml-research/issues/7) from probml-research
=> feat:  `intrinsic_dimension_toy_demo.py`

scripts/subspace_mlp_demo.py
Replicates Figure 2 (left) from the [Measuring the Intrinsic Dimension of Objective Landscapes paper](https://arxiv.org/abs/1804.08838) from Li, et.al
=> create: `subspace_mlp_demo.py`

scripts/lds_lib.py
=> KalmanFilterNoiseEstimation

scripts/sis_vs_smc.py
We replicate Figures 2, 3, and 4 from the paper
> Christian A. Naesseth, Fredrik Lindsten, Thomas B. Schön: “Elements of Sequential Monte Carlo”, 2019; arXiv:1903.04797
For the code implementation see [here](https://github.com/probml/JSL/blob/main/jsl/nlds/sequential_monte_carlo.py).
=> create: sis_vs_smc.py

scripts/adf_logistic_regression_demo.py
=> refactor: adf_logistic_regression

.github/workflows/main.yml, .pre-commit-config.yaml, _config.yml, _toc.yml, auto_generated_scripts/README.md, intro.md, notebooks/README.md, pytest.ini, requirements.txt, tests/test_notebooks.py, tests/test_scripts.py
Added GitHub Actions workflow and initialized the jupyter-book.
#702
=> Add workflow and jupyter-book setup

scripts/bocd.py
Implementation of the Bayesian online change point detection (BOCD) model for a univariate Gaussian with fixed precision and varying mean.
Closes #680
=> Create: bocd.py

scripts/linear_bandit.py
https://github.com/probml/pyprobml/issues/699
https://github.com/probml/pyprobml/issues/699#issuecomment-1086777028
=> Add linear_bandit.py supporting UCB and epsilon greedy exploration

scripts/transposed_conv_jax.py
Converted `transposed_conv_torch.py`  to `transposed_conv_jax.py`
Colab link to compare with the torch script: https://colab.research.google.com/drive/1kJiHOlBs1wkDPPA7QyDNa9eDmf0aZaEc?usp=sharing
The outputs are the same as the torch version.
Can you have a review? @murphyk @mjsML @gerdm
https://github.com/probml/pyprobml/issues/745
=> Add `transposed_conv_jax.py`

notebooks/book1/02/robust_pdf_plot.ipynb
Hello Dr @murphyk , 
I am [Nitish Sharma](https://github.com/nitish1295?tab=repositories), I am working alongside Prof @nipunbatra  and Lab colleagues @patel-zeel and @karm-patel . I have updated robust_pdf_plot.ipynb based on the contribution guidelines and feedback from fellow colleagues. Kindly find time to review the notebook
Added robust_pdf_plot.ipynb for [robust_pdf_plot.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/02/robust_pdf_plot.ipynb)
Book 1 - 2.16 (a) and (b)
[gist](https://gist.github.com/nitish1295/60a7baaffdf0680534bc32450ebe40f9)
#739 
- Updated the y-axis range to ensure the Laplacian PDF is visible correctly Fig 2.16 (a)
- Updated the plot to ensure gaussian PDF is now visible in Fig 2.16 (a)
=> Updated robust_pdf_plot

notebooks/README.md
Added Python version instructions in `notebook/README.md`.
#762
=> Mention Python version in `README`

notebooks/book1/03/gauss_imputation_known_params_demo.ipynb
Added gauss_imputation_known_params_demo.ipynb for [gauss_imputation_known_params_demo.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/03/gauss_imputation_known_params_demo.ipynb)
Book 1 - 3.7
[gist](https://gist.github.com/nitish1295/7b6a72e4587e5b66e66b45a2148b7be1)
#739 
- Updated patches to appear over grid so that they are visible more clearly
- Updated patch size to ensure that it is uniform across figures
=> Updated gauss_imputation_known_params_demo

.github/workflows/notebooks.yml, notebooks/README.md
Python 3.7.13 in workflow and development ensures that code runs fine on Google colab.
#762
=> pin Python 3.7.13 in workflow

notebooks/book1/03/gauss_infer_1d.ipynb
Added gauss_infer_1d.ipynb for [gauss_infer_1d.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/03/gauss_infer_1d.ipynb)
Book 1 - 3.8
[gist](https://gist.github.com/nitish1295/797220d030b453bbbb5d9798aac0a2d2)
https://github.com/probml/pyprobml/issues/739
- Updated x-axis to show complete graphs
=> Updated gauss_infer_1d

.github/workflows/notebooks.yml, requirements-bash.txt
There are some python packages that depend on ubuntu packages, I have added `requirements-bash.txt` and added a code in `notebooks.yml` to install them.
=> Add  `requirements-bash.txt`

.github/workflows/notebooks.yml
Cache TSDF and PyTorch datasets to save time in workflow.
https://github.com/probml/pyprobml/issues/783
GitHub actions only cache things when the workflow run is successful, which makes sense since there could be a network glitch resulting in partially downloaded datasets. However, most workflow runs are unsuccessful at this time, so the cache is not particularly useful. Hopefully, the situation will improve over time.
=> Add dataset caching

notebooks/book1/16/parzen_window_demo2.ipynb
Hello, Dr @murphyk,
I am Rohit Khoiwal, and I got my internship at IITGN under Prof. Nipun Batra. I have updated the notebook [parzen_window_demo2.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/16/parzen_window_demo2.ipynb) that gives error for saving figures. I used pyprobml repo with the help of @patel-zeel and @karm-patel to resolve that error.
Book1 - 16.9
#759 
- It's important to use the try-except block for importing the module.
=> Fix workflow error in parzen_window_demo2.ipynb

notebooks/book1/04/gauss_infer_1d.ipynb, notebooks/book1/04/gauss_infer_2d.ipynb, notebooks/book1/10/iris_logreg.ipynb, notebooks/book1/11/huberLossPlot.ipynb, notebooks/book1/11/linreg_poly_vs_degree.ipynb, notebooks/book1/13/activation_fun_plot.ipynb, notebooks/book1/17/huberLossPlot.ipynb, notebooks/book1/18/hinge_loss_plot.ipynb, notebooks/book1/21/gmm_2d.ipynb
Convert GitHub redirection URLs to colab URLs.
=> GitHub to colab

notebooks/book1/17/gprDemoArd.ipynb
Hello Dr.@murphyk,
I work with Prof.@nipunbatra and his team at IIT Gandhinagar.
I have resolved the workflow error in book1/17/gprDemoArd.ipynb. Please have a look.
`book1-17.1`
#759
=> fixed workflow error in gprDemoArd.ipynb

internal/book2/create_dummy_notebook.py, internal/book2/create_figure_url_mapping.py, internal/book2/delete_firestore.py, internal/book2/postprocessing.py, internal/book2/update_firestore.py, internal/book2/wrap_with_try_except.py
1. Added `delete_firestore.py` to delete all keys from firestore
2. Handled the case of deleting existing dummy multi-notebooks
=> Book2: Handle automated pipeline to update fig in database

.github/scripts/combine_results.py, .github/scripts/create_dashboard.py, .github/workflows/notebooks.yml
- Currently, all log links in the dashboard are broken due to some issue. fixed `workflow_test_indicator/README.md`.
=> Book2: Fix  workflow broken log links

notebooks/book1/02/change_of_vars_demo1d.ipynb
Book 1 - fig 2.24
| Before PR | ![fig 2 24](https://user-images.githubusercontent.com/87682045/169258033-1c2ab613-9157-40ef-9502-2157eb360be2.PNG) |
| ------------| ----------|
| After PR    |  ![fig 2 24 latexified](https://user-images.githubusercontent.com/87682045/169586276-d33c3648-322e-4ad0-855c-cfcef6e50042.PNG)|
#739
=> Fixs : Fig 2.24 book1/change_of_vars_demo1d

notebooks/book2/04/gibbs_demo_ising.ipynb
- Latexified and Jaxified Book2 - Fig 4.16 `gibbs_demo_ising.ipynb`
- I added `jax.lax.scan` since native JAX loop was taking too much time for sampling.
Book2 - Fig 4.16
**Before PR**:
**After PR**:
#893 
cc - Dr. @murphyk, Prof. @nipunbatra
=> Latexified and Jaxified Book2 - Fig 4.16 `gibbs_demo_ising.ipynb`

notebooks/book1/04/samplingDistributionGaussianShrinkage.ipynb
Latexified, jaxified, and added interactive plot for `samplingDistributionGaussianShrinkage.ipynb`
`book1/4.24`
| Before PR |![before](https://user-images.githubusercontent.com/54628243/172064967-b650cd9b-c235-4b52-b179-ecef207d292a.png)|
| :-: | :-: |
|After PR|![after](https://user-images.githubusercontent.com/54628243/172064978-b85b88ab-afaf-43ea-9175-8eec42266d95.png)|
#790
=> jaxified and latexified notebook samplingDistributionGaussianShrinkage.ipynb

notebooks/book1/02/softmax_plot.ipynb
Hello Dr. @murphyk, I am [Taksh](https://github.com/takshpanchal), I am working with Prof @nipunbatra  and  @karm-patel . I have updated softmax_plot.ipynb based on the contribution guidelines and feedback from @karm-patel. Kindly review the notebook
Updated softmax_plot.ipynb for [softmax_plot.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/02/softmax_plot.ipynb)
Book 1 - 2.12
| :-: | :-: |
|![image](https://user-images.githubusercontent.com/52617262/171986977-32b84df0-9906-4452-93ee-f5dab088056b.png)|![Image](https://user-images.githubusercontent.com/52617262/174423682-8e6a51c6-73cf-4312-b373-90a3ad24dbd1.png)
-->
#739
=> updated fig-2.12 of book1

notebooks/book2/02/pareto_dist_plot.ipynb
Figure 2.3 of Book2 - pareto_dist_plot.ipynb
| :-: | :-: |
| ![before](https://user-images.githubusercontent.com/52617262/175473833-f2531996-b24c-4835-9413-c5ddf4d1d2c4.png) |![image](https://user-images.githubusercontent.com/52617262/175862999-e094ae02-a527-4a9c-b5fc-9bb67cd937c8.png)|
#739
=> figure 2.3 of book2 pareto_dist_plot.ipynb

notebooks/book2/05/bernoulli_entropy_fig.ipynb
Hi Dr. @murphyk, I am Dhruv Patel a student working under Prof. @nipunbatra.
I have latexified the below figure. Kindly review it [here.](https://colab.research.google.com/drive/1tCJoydn2-bvYGsAMPoe_hgSqWQT4KOd0?usp=sharing)
Book2 - 5.3
| :-: | :-: |
|![before pr](https://user-images.githubusercontent.com/76422222/176254721-2349bebc-bec5-4aab-b480-623f04f00218.png)|![after pr](https://user-images.githubusercontent.com/76422222/176254804-5a271e3e-f366-48a3-b8ad-9c505cb5ff57.png)|
#900
- latexified the figure.
- adjusted the height of the figure.
=> latexified fig 5.3 of Book2

notebooks/book2/18/deepgp_stepdata.ipynb
Hello, Dr.@murphyk; this PR creates code for figures 18.31 and 18.32 of Book2 and latexifies them.
book2 - 18.31
book2 - 18.32
| :-: | :-: |
|<img width="677" alt="Fig_18 31_book" src="https://user-images.githubusercontent.com/68186100/176913745-a61af1fd-a188-4c67-8e3a-cb495c52df75.png">|<img width="677" alt="Fig_18 31" src="https://user-images.githubusercontent.com/68186100/176913733-92a7d29d-cc45-468f-b851-c7d242e22f15.png">
| :-: | :-: |
|<img width="514" alt="Fig_18 32_book" src="https://user-images.githubusercontent.com/68186100/176913752-c416056a-e9d6-45fb-b6df-48c160826fe6.png">|<img width="514" alt="Fig_18 32" src="https://user-images.githubusercontent.com/68186100/176913747-6d30abf5-64d2-43e0-8489-df2c1d75d0da.png">
#739
* Used …
=> fixes Issue #739 Book2 Fig 18.31 and Fig 18.32

notebooks/book2/19/bnn_mnist_sgld.ipynb, notebooks/book2/19/bnn_mnist_sgld_sgmcmcjax.ipynb
Added `flax` & `blackjax` implementation of SGLD.
Fig 19.8, 19.9
- 19.8
Before:
After:
- 19.9
Before:
After:
#856
=> Added `bnn_mnist_sgld.ipynb`

notebooks/book2/03/newcomb_plugin_demo.ipynb
=> Latexified newscomb notebook

notebooks/book2/34/al_sensor_placements.ipynb, notebooks/book2/34/bayes_opt_vs_active_learning.ipynb
#1016 
Added two notebooks that generate figures in active learning chapter.
=> AL notebooks added

notebooks/book2/34/Batchbald_implementation.ipynb
Added a notebook for BALD and BatchBALD implementation. The code generates the test accuracy curve and the samples picked up by BALD and BatchBald techniques.
| Title | Figures |
| :-: | :-: |
| Samples Selected | ![image](https://user-images.githubusercontent.com/62535006/180255079-17b6ea9d-fcf6-4e72-8929-eab430a46bc1.png) |
| Test Accuracy Curve | ![image](https://user-images.githubusercontent.com/62535006/180255769-55d00dba-8f97-4dd6-8517-2c15d09b30f5.png) |
#1016
=> Batchbald_implementation

notebooks/book2/17/mnist_classification_mc_dropout.ipynb
Added Figure in which we can see the model uncertainty in softmax output and we adapted this figure from [Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning.](https://arxiv.org/abs/1506.02142)
| Softmax Input scatter | Softmax output scatter |
| :-: | :-: |
|![mnist_softmax_input_latexified-1](https://user-images.githubusercontent.com/87682045/181008296-cd119231-b479-4f7c-848a-bf2918310ea5.png)|![mnist_softmax_output__latexified-1](https://user-images.githubusercontent.com/87682045/181008352-8c2a335b-0afc-4e7a-a2f1-480e637ecb1f.png)|
=> Added mnist_classification_mc_dropout notebook

.github/scripts/generate_notebooks_md.py
Updated index generation script to allow non-numeric notebook directories which do not represent chapter numbers.
=> Update index generation script
