probml/pyprobml

book/nat_grad_demo.py
runs slow with 1000000 points but can be reduced to 1000 to run quickly. Next step will be to add some comments to clarify a lot of the math. Similarly, it should be noted that the G\dL step in python is solved using least squares which can have different shapes than the MatLab solver according to this https://stackoverflow.com/questions/33559946/numpy-vs-mldivide-matlab-operator. 
Additionally, the original MatLab file did not have any names for the output figures. As such, I included save_fig with seemingly reasonable names, but these can easily be removed if desired.
=> add the natural gradient demo, with save figures, 

scripts/knn_voronoi_plot.py
Original version use
```
x = np.linspace(0, 1, 200)
y = np.linspace(0, 1, 200)
```
while xlim and ylim of the figure generated by `voronoi_plot_2d` does not have to be [0, 1].
=> Let the size of the 2nd figure be same as the 1st

scripts/mix_gauss_singularity.py
Add script to illustrate singularities in the likelihood function of GMMs (section 5.19)
The script produces the following image:
=> add gmms singularities diagram

scripts/parzen_window_demo2.py
* Add Python script that replicates figure 14.7 (PML 1st edition / parzenWindow2)
The following image is the result of the script
=> add parzen-window2 example

scripts/gaussInferParamsMean1d.py
Added python implementation of gaussInferParamsMean1d.
Fixes #177
=> Added implementation of gaussInferParamsMean1d

scripts/kernelRegressionDemo.py
#215  (kernelRegressionDemo.py)
@murphyk, @mjsML
I have already done this with the PR #311, but as you asked for a light-weight solution I have implemented the smoother in this code
Figure:
=> Implemented NW Smoother

scripts/gaussImputationDemo.py
Closes #171
I implemented gauss Imputation basing it on gaussImpute() and gaussCondition() matlab files in pmtk3.googlecode.com.
To randomly create sigma, I have used the sci-kit learn library instead of implementing randpd because of the excessive time delay in creating a positive semidefinite matrix as the probability of creating one SPD using randpd in python is less than 1.
Please note that the MATLAB implementation has randomly generated a matrix of size 20x10 but in the book I observed that a matrix of 8x10 is provided, therefore I provided the inputs d=8 and n=10, but the dimensions of the matrix can be changed by altering n & d in the code.
Updated the code to include the following changes:
1. use longer, more readable variable names, and follow PEP8 conventions, even if this …
=> Converted gaussImputationDemo to python

scripts/mean_shift_opt.py
@murphyk and @mjsML , please review this. Here, ‘import jax.numpy as jnp’ is commented out and not used. Is this required to be changed?
#369
=> Use jax.numpy consistently (mean_shift_opt.py)

scripts/student_pgm_inf_autodiff.py
Resolved bug in the file `student_pgm_inf_autodiff.py` by reshaping the arrays and adding `joint=False` arguement in infer_pgmpy function.
Fixes #432
=> Resolved bug in the file student_pgm_inf_autodiff.py

scripts/linearrobustdemocombined.py
@murphyk and @mjsML , please review this code. Here, I have tried to use `sklearn` as much as possible and the `statsmodels` package has been useful for student-t distribution loss. In the statsmodels package, in the files, edgeworth.py, markov_switching.py, kernels.py, functional.py, moment_helpers.py imports like `from scipy.misc import factorial` or from` scipy.misc import logsumexp` should be changed to `scipy.special import factorial/logsumexp` as these functions are located in `scipy.special` (for scipy >=1.3.0)
Closes #203 
Fig. 11.9 :
=> Convert_LinearRobustDemoCombined_to_python

scripts/gibbs_gauss_demo.py
Replicate `gibbsGaussDemo.m` for vol 2 book.
The script produces the following figure.
=> add gibbs_gauss_demo.py

notebooks/logreg_ucb_admissions_numpyro.ipynb
Closes probml/hermes#78
Only, `notebooks/logreg_ucb_admissions_numpyro.ipynb` dont have explicit args, all other numpyro scripts and notebooks either dont use MCMC or are following the updated API
@murphyk
=> Updated numpyro code to use new MCMC() interface

scripts/hmm_casino_demo.py, scripts/hmm_lib.py
Defines HMMDiscrete class and script that replicates the figures on the casino HMM example. The script also prints out a sample of the simulated data.
28.9 PML Vol 2
Output data example
```
x: 666333434452361543336162146653316146656663144434652652444446
z: 222222221111111111111111111111111112222222222222222211111111
```
Closes #37
=> add hmm_casino_demo.py, hmm_lib.py

scripts/linear_dynamical_systems_lib.py, scripts/parallel_kalman_filter_demo.py
1. Generalises code to work with the parallel and the single case. It won't break either code
2. Removes `ParallelLinearDynamicalSystem` class
3. `parallel_kalman_filter_demo.py` now considers `LinearDynamicalSystem` to execute the code
4. Simulation of LDS considers einsums (raison d'etre above)
5. Figure output of `parallel_kalman_filter_demo.py` is the following
Furthermore, replace greek symbols for English ASCII in ` scripts/linear_dynamical_systems_lib.py` for usability
For example. Change:
```python
K1 = self.Σ0 @ self.C.T @ inv(self.C @ self.Σ0 @ self.C.T + self.R)
μ1 = self.μ0 + K1 @ (x_hist[0] - self.C @ self.μ0)
Σ1 = (I - K1 @ self.C) @ self.Σ0
μ_hist = index_update(μ_hist, 0, μ1)
Σ_hist = index_update(Σ_hist, 0, Σ1)
μ_cond_hist = index_update(μ_cond_hist, 0, self.μ0) …
```
=> Parallel Kalman Filtering and refactor

scripts/kalman_filter_spiral_demo.py
Creates demo that exemplifies the behaviour of the Kalman Filter equations when the transition matrix has imaginary eigenvalues.
=> feat: create kalman_filter_spiral_demo.py

scripts/ekf_vs_ukf_demo.py, scripts/nlds_lib.py
* Refactor `nlds_lib.py` class
* Refactor `ekf_vs_ukf` demo
* No change in output
Closes [issue 216](https://github.com/probml/hermes/issues/216) in Hermes
For flexibility, I propose the `.from_base` classmethod. This allows us to optionally separate the model initialisation from the "filtering" process. With this classmethod, we can initialise the dynamical system as a separate entity
```python
model = ds.NLDS(lambda x: fz(x, dt), fx, Qt, Rt)
sample_state, sample_obs = model.sample(key, x0, nsteps)
ekf = ds.ExtendedKalmanFilter.from_base(model)
ukf = ds.UnscentedKalmanFilter.from_base(model, alpha, beta, kappa)
```
or implicitly as a single class
```python
ekf = ds.ExtendedKalmanFilter(lambda x: fz(x, dt), fx, Qt, Rt)
sample_state, sample_obs = ekf.sample(key, x0, nsteps)
```
=> Refactor `nlds_lib.py`

scripts/ekf_vs_ukf_mlp_demo.py, scripts/nlds_lib.py
* Refactor `nlds_lib.py`: optional parameters for `fx`
* Fix `nlds_lib.py`: UKF sigma-points specification and use
* Create demo of training a single-layered MLP with EKF and UKF using `nlds_lib.py`
Closes [issue 54](https://github.com/probml/hermes/issues/54) in Hermes
=> create EKF/UKF + MLP

scripts/bootstrap_filter_demo.py, scripts/nlds_lib.py
* Fix bug for the `ExtendedKalmanFilter` and `ContinuousExtendedKalmanFilter` classes: incorrect computation of the filtering step
* Add resampling of points for the bootstrap filtering (as explained in Algorithm 7.5 of  Särkkä)
The figures change as follows (left is old, right is new):
Output of `ekf_vs_ukf_demo.py`
<p float="left">
</p>
Output of `bootstrap_filter_demo.py`
<p float="left">
</p>
=> fix `nlds_lib.py`

scripts/mcmc_gmm_demo.py, scripts/pyprobml_utils.py, scripts/rbpf_maneuver_demo.py
* Refactor `mcmc_gmm_demo.py` and `pyprobml_utils.py` to make use of 3d plot functions in `pyprobml_utils`
* No change in figures
Closes [issue #326](https://github.com/probml/hermes/issues/326) in Hermes
=> Refactor: Move 3d-plots functions to pyprobml_utils

scripts/stick_breaking_demo.py
Convert stickBreakingDemo.m to python. 
Figure 28.3.
Figure from Python
Original figure from MATLAB
Closes #612
=> Convert stickBreakingDemo.m to python

scripts/perceptron_demo_2d.py
Could not import the scikit-learn perceptron model when running the code locally. Very minor changes to the import and initialization lines to fix the issue.
=> Fix: sklearn model import and initialization

scripts/pgmpy_utils.py
This bug is caused by taking the transpose of the `values` array before reshaping it into an `n x m` matrix. It's not a problem when `cpd.values.ndim <= 2` but at higher dimensions, the dimensions get mixed up.
Volume 02 - Figure 4.2
https://gist.github.com/UmarJ/19cf663ec4f9033841d3c166d31d3ba8
The gist also has another example.
Resolves #733
=> Fix `visualize_model` for `cpd.values.ndim > 2`

scripts/conditional_bernoulli_mix_utils.py, scripts/fit_flax.py, scripts/mix_gauss_mle_vs_map_jax.py, scripts/vb_gauss_cholesky.py
Replace deprecated `jax.tree_multimap` with `jax.tree_map` to avoid the deprecation warning.
```
xxx/.venv/lib/python3.10/site-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
warnings.warn('jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() '
```
[Deprecate jax.tree_util.tree_multimap](https://github.com/google/jax/pull/10126)
[Replace `jax.tree_multimap` with `jax.tree_map`](https://github.com/probml/probml-notebooks/issues/83) (I'm linking the `probml-notebooks` issue. Should I open a separate issue in `pyprobml`?)
Since `tree_multimap` is just an alias for `tree_map`, I did a very trivial fix with `ag` and `sed`. I have manually reviewed …
=> Replace deprecated `jax.tree_multimap` with `jax.tree_map`

.github/workflows/notebooks.yml, tests/test_notebooks.py
Dead simple parallel CI workflow with 20 runners. Feel free to increase the number of concurrent jobs to 40 or something as long as it falls under the [usage limit](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits).
https://github.com/probml/pyprobml/issues/783
It's too risky to make use of [actions/cache@v3](https://github.com/actions/cache) without pinning the exact version of all packages, so this PR only implements parallel CI.
=> Simple parallel CI workflow

.github/scripts/combine_results.py, .github/scripts/create_dashboard.py, .github/workflows/notebooks.yml, .gitignore, tests/test_notebooks.py
This PR extends the functionality of #792 and partially addresses #783.
After this PR, the workflow will:
* Push figures to `auto_generated_figures` branch
* Push workflow status to `workflow_testing_indicator` branch
* Automatically create a [dashboard](https://github.com/probml/pyprobml/blob/workflow_testing_indicator/README.md) containing the status of the workflow.
Steps:
=> Combine and publish results from parallel workflows

.github/workflows/notebooks.yml, notebooks/book1/01/cifar_viz_tf.ipynb, notebooks/book1/01/emnist_viz_jax.ipynb, tests/test_notebooks.py
Added a separate step to check the latest modified notebooks to easily find out the problems with them.
I have also added a step named "Display notebook modification time" so that we can check which notebooks have been touched recently, e.g.
```
1652335564 notebooks/book1/01/cifar_viz_tf.ipynb
1652315872 notebooks/book2/20/LVAE.ipynb
1652315872 notebooks/book2/17/gprDemoNoiseFreeAndNoisy.ipynb
1652315872 notebooks/book2/17/gprDemoArd.ipynb
```
https://github.com/probml/pyprobml/issues/783#issuecomment-1124509364
The new `execute_latest_notebooks` stage is not parallelized to keep things easy on the eyes. We typically don't touch a lot of notebooks in one commit anyway.
=> Add new workflow stage to check latest notebooks

notebooks/book2/04/gibbs_demo_ising.ipynb
The contribution of the lower y pixel is assigned to an unused variable a instead of to wi.
book2 Figure 4.17
| :-: | :-: |
|![image](https://user-images.githubusercontent.com/12573521/189524494-812bad74-2f3a-4891-8451-e55f1c5039a7.png)|![image](https://user-images.githubusercontent.com/12573521/189524417-256765bc-f14a-413b-9b0f-8ddf3e333482.png)
|![image](https://user-images.githubusercontent.com/12573521/189524519-7c85f243-64fa-45f4-b802-5ad8e61c6f47.png)|![image](https://user-images.githubusercontent.com/12573521/189524454-877105d5-5a2b-4103-bbbd-b8c04ffcdabf.png)
|![image](https://user-images.githubusercontent.com/12573521/189524556-8a827bd9-ec01-47ab-8ef6-9902b476945c.png)|![image](https://user-images.githubusercontent.com/12573521/189524469-a1823eff-baed-4ec7 …
=> Minor bug in computing the energy of ising demo.
